# Generated by Django 5.1.7 on 2025-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="farm_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
